services:
  game-server:
    build: ./server
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - game-network
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - game-sessions:/app/sessions
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', res => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.2-alpine
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - game-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-exporter:
    image: oliver006/redis_exporter:v1.55.0
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    networks:
      - game-network

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - game-network
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Важно!
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - game-server

  prometheus:
    image: prom/prometheus:v2.47.2
    ports: []
    networks:
      - game-network
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - ./nginx/secrets/.htpasswd-prometheus:/etc/nginx/.htpasswd-prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  node-exporter:
    image: prom/node-exporter:v1.7.0
    networks:
      - game-network
    volumes:
      - /:/host:ro,rslave
    pid: host
    privileged: true
    command:
      - '--path.rootfs=/host'

  grafana:
    image: grafana/grafana:10.1.5
    ports: []
    networks:
      - game-network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.coobe.ru
      - GF_SERVER_SERVE_FROM_SUB_PATH=false

volumes:
  redis_data:
  game-sessions:
  prometheus_data:
  grafana_data:

networks:
  game-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24