services:
  game-server:
    build: ./server
    networks:
      - game-network
    environment:
      - NODE_ENV=production
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    networks:
      - game-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - game-network
    depends_on:
      game-server:
        condition: service_started

volumes:
  redis_data:

networks:
  game-network:
    name: game-network
    driver: bridge