global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'game-server'
    static_configs:
      - targets: ['game-server:3000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']