global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'game-server'
    static_configs:
      - targets: ['game-server:3000']

  - job_name: 'redis-exporter'  # Исправленное имя
    static_configs:
      - targets: ['redis-exporter:9121']