global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'game-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['game-server:3000']

  - job_name: 'redis'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']